# Generated by Django 2.2.2 on 2019-07-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='test@test.com', max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('blogPost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.BlogPost')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField(default='http://localhost', null=True)),
                ('facebook_link', models.URLField(default='http://localhost', null=True)),
                ('Linkedin_link', models.URLField(default='http://localhost', null=True)),
                ('Instagram_link', models.URLField(default='http://localhost', null=True)),
                ('Telegram_link', models.URLField(default='http://localhost', null=True)),
                ('Telegram_ID', models.CharField(default='http://localhost', max_length=200, null=True)),
                ('aboutme', models.TextField(default='No Informations!')),
                ('primary_skill', models.ForeignKey(default='Dumb', on_delete=django.db.models.deletion.CASCADE, related_name='user_who_have_this_as_primary', to='weblog.Skill')),
                ('secondary_skill', models.ForeignKey(default='Dumb', on_delete=django.db.models.deletion.CASCADE, related_name='user_who_have_this_as_secondary', to='weblog.Skill')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.Comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail'),
        ),
        migrations.CreateModel(
            name='BlogPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=0)),
                ('blogPost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.BlogPost')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail'),
        ),
    ]
