# Generated by Django 2.2.2 on 2019-07-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=250)),
                ('blogPost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.BlogPost')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('github_link', models.URLField(null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('Linkedin_link', models.URLField(null=True)),
                ('Instagram_link', models.URLField(null=True)),
                ('Telegram_link', models.URLField(null=True)),
                ('Telegram_ID', models.CharField(max_length=200, null=True)),
                ('aboutme', models.TextField(default='No Informations!')),
                ('primary_skill_score', models.IntegerField()),
                ('secondary_skill_score', models.IntegerField()),
                ('primary_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_skill', to='weblog.Skill')),
                ('secondary_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_skill', to='weblog.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('blogPost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.BlogPost')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.Comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail'),
        ),
    ]
