# Generated by Django 2.2.2 on 2019-07-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='admin',
            field=models.BooleanField(default=0),
        ),
    ]
