# Generated by Django 2.2.2 on 2019-07-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_auto_20190707_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='primary_skill_score',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='secondary_skill_score',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='primary_skill',
            field=models.ForeignKey(default='Dumb', on_delete=django.db.models.deletion.CASCADE, related_name='user_who_have_this_as_primary', to='weblog.Skill'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='secondary_skill',
            field=models.ForeignKey(default='Dumb', on_delete=django.db.models.deletion.CASCADE, related_name='user_who_have_this_as_secondary', to='weblog.Skill'),
        ),
    ]
