# Generated by Django 2.2.2 on 2019-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_auto_20190707_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='signup_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
