# Generated by Django 2.2.2 on 2019-07-16 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_auto_20190716_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostlike',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='blogpostlike',
            unique_together={('blogPost_id', 'username')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment_id', 'username')},
        ),
    ]
