# Generated by Django 2.2.2 on 2019-07-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_auto_20190707_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail'),
        ),
    ]
