# Generated by Django 2.2.2 on 2019-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_userdetail_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='weblog/profile_pics'),
        ),
    ]
