# Generated by Django 2.2.2 on 2019-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_auto_20190717_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='rank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
