# Generated by Django 2.2.2 on 2019-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_userdetail_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='weblog/<django.db.models.fields.related.OneToOneField>/profile_pics'),
        ),
    ]
