# Generated by Django 2.2.2 on 2019-07-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostlike',
            name='username',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='username',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='weblog.UserDetail'),
        ),
    ]
