# Generated by Django 2.2.2 on 2019-07-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_auto_20190707_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostlike',
            name='likes',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='likes',
            field=models.BooleanField(default=0),
        ),
    ]
