# Generated by Django 2.2.2 on 2019-07-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_auto_20190717_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Telegram_ID',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
