# Generated by Django 2.2.2 on 2019-07-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_auto_20190717_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='bio',
            field=models.TextField(default='No Informations!'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='aboutme',
            field=models.CharField(default='No Informations!', max_length=50),
        ),
    ]
