# Generated by Django 2.2.2 on 2019-07-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_auto_20190707_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Instagram_link',
            field=models.URLField(default='http://', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Linkedin_link',
            field=models.URLField(default='http://', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Telegram_ID',
            field=models.CharField(default='http://', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Telegram_link',
            field=models.URLField(default='http://', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='facebook_link',
            field=models.URLField(default='http://', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='github_link',
            field=models.URLField(default='http://', null=True),
        ),
    ]
