# Generated by Django 2.2.2 on 2019-07-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0011_auto_20190709_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Instagram_link',
            field=models.URLField(default='http://localhost', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Linkedin_link',
            field=models.URLField(default='http://localhost', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Telegram_ID',
            field=models.CharField(default='http://localhost', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Telegram_link',
            field=models.URLField(default='http://localhost', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='facebook_link',
            field=models.URLField(default='http://localhost', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='github_link',
            field=models.URLField(default='http://localhost', null=True),
        ),
    ]
