# Generated by Django 2.2.2 on 2019-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0012_userdetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='aboutme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
