# Generated by Django 2.2.2 on 2019-07-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0013_auto_20190711_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='account_status',
            field=models.CharField(default='Active', max_length=250),
        ),
    ]
