# Generated by Django 2.2.2 on 2019-07-18 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0013_auto_20190718_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='weblog//profile_pics'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
