# Generated by Django 2.2.2 on 2019-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0016_auto_20190718_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='weblog/<django.db.models.fields.related.OneToOneField>/profile_pics'),
        ),
    ]
