# Generated by Django 2.2.2 on 2019-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0017_auto_20190718_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='weblog/profile_pics'),
        ),
    ]
