# Generated by Django 2.2.2 on 2019-07-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0018_auto_20190719_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_pic',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='weblog/post_pics', width_field=750),
        ),
    ]
