# Generated by Django 2.2.2 on 2019-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0019_blogpost_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to='weblog/post_pics'),
        ),
    ]
